name: Clean up old emails in Gmail accounts
on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '30 6 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 src --count --max-complexity=10 --max-line-length=120 --show-source --statistics
    - name: Test with pytest
      run: |
        pytest --cov=src

    - name: Clean up old emails in Gmail account 1
      env:
        RECIPIENT_EMAIL_ADDRESS: dummy
        FROM_EMAIL_ADDRESS: dummy
        FROM_EMAIL_PASSWORD: dummy
        NOTION_API_TOKEN: dummy
        NOTION_TASKS_DB_ID: dummy
        NEWS_API_TOKEN: dummy
        GMAIL_OLDER_THAN_DAYS: ${{secrets.GMAIL_1_OLDER_THAN_DAYS}}
        GMAIL_EMAIL_ADDRESS: ${{secrets.GMAIL_1_EMAIL_ADDRESS}}
        GMAIL_PASSWORD: ${{secrets.GMAIL_1_PASSWORD}}
      run: |
        python -c 'from src.tasks.email_cleaner import task; task()'
