name: Clean up old emails in Gmail accounts
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '30 6 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v7
    
    - name: Set up Python
      run: uv python install

    - name: Lint code
      run: |
        uv run flake8 src --count --max-complexity=10 --max-line-length=120 --show-source --statistics

    - name: Run tests
      run: uv run pytest --cov=src

    - name: Clean up old emails in Gmail account 1
      env:
        RECIPIENT_EMAIL_ADDRESS: dummy
        FROM_EMAIL_ADDRESS: dummy
        FROM_EMAIL_PASSWORD: dummy
        NOTION_API_TOKEN: dummy
        NOTION_TASKS_DB_ID: dummy
        NEWS_API_TOKEN: dummy
        GMAIL_OLDER_THAN_DAYS: ${{vars.GMAIL_1_OLDER_THAN_DAYS}}
        GMAIL_EMAIL_ADDRESS: ${{vars.GMAIL_1_EMAIL_ADDRESS}}
        GMAIL_PASSWORD: ${{secrets.GMAIL_1_PASSWORD}}
      run: |
        uv run python -c 'from src.tasks.email_cleaner import task; task()'

    - name: Clean up old emails in Gmail account 2
      env:
        RECIPIENT_EMAIL_ADDRESS: dummy
        FROM_EMAIL_ADDRESS: dummy
        FROM_EMAIL_PASSWORD: dummy
        NOTION_API_TOKEN: dummy
        NOTION_TASKS_DB_ID: dummy
        NEWS_API_TOKEN: dummy
        GMAIL_OLDER_THAN_DAYS: ${{vars.GMAIL_2_OLDER_THAN_DAYS}}
        GMAIL_EMAIL_ADDRESS: ${{vars.GMAIL_2_EMAIL_ADDRESS}}
        GMAIL_PASSWORD: ${{secrets.GMAIL_2_PASSWORD}}
      run: |
        uv run python -c 'from src.tasks.email_cleaner import task; task()'
