name: Send daily email report
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 3 * * *" 
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install uv
      uses: astral-sh/setup-uv@v7
    
    - name: Set up Python
      run: uv python install

    - name: Lint code
      run: |
        uv run --group lint flake8 src --count --max-complexity=10 --max-line-length=120 --show-source --statistics

    - name: Run tests
      run: uv run --group test pytest --cov=src

    - name: Run the daily report task
      env:
        RECIPIENT_EMAIL_ADDRESS: ${{secrets.RECIPIENT_EMAIL_ADDRESS}}
        FROM_EMAIL_ADDRESS: ${{secrets.FROM_EMAIL_ADDRESS}}
        FROM_EMAIL_PASSWORD: ${{secrets.FROM_EMAIL_PASSWORD}}
        NOTION_API_TOKEN: ${{secrets.NOTION_API_TOKEN}}
        NOTION_TASKS_DB_ID: ${{secrets.NOTION_TASKS_DB_ID}}
        NEWS_API_TOKEN: ${{secrets.NEWS_API_TOKEN}}
        GMAIL_OLDER_THAN_DAYS: dummy
        GMAIL_EMAIL_ADDRESS: dummy
        GMAIL_PASSWORD: dummy
      run: |
        uv run python -c 'from src.tasks.daily_email_reports import task; task()'
